id = "axe"
kind = "item"

[visual]
glb = "assets/models/optimized/spear.glb"
[visual.lod]
near = "assets/models/optimized/spear.glb"
mid  = "assets/models/optimized/herrscher_of_truths_spear.glb"
far  = "assets/models/optimized/herrscher_of_truths_spear.glb"

[sim]
weight_milli = 250
gather_bonus = 25
uses = 8
[sim.craft]
inputs = [["wood", 2], ["stone", 1]]
output_qty = 1
