id = "hoe"
kind = "item"

[visual]
glb = "assets/models/optimized/spear.glb"
[visual.lod]
near = "assets/models/optimized/spear.glb"
mid  = "assets/models/optimized/herrscher_of_truths_spear.glb"
far  = "assets/models/optimized/herrscher_of_truths_spear.glb"

[sim]
weight_milli = 200
farm_bonus = 25
uses = 8
[sim.craft]
inputs = [["stone", 1], ["wood", 1]]
output_qty = 1
