id = "millstone"
kind = "item"

[visual]
glb = "assets/models/optimized/stones_and_grass.glb"
[visual.lod]
near = "assets/models/optimized/stones_and_grass.glb"
mid  = "assets/models/optimized/stones_and_grass.glb"
far  = "assets/models/optimized/stones_and_grass.glb"

[sim]
weight_milli = 800
[sim.craft]
inputs = [["stone", 3]]
output_qty = 1
